### ISSUE TITLE
Actual Cash-on-Hand Negative Values

### ISSUE THREAD

**Issue by nikkinicholasromero** [nikkinicholasromero/GTYDSR#7]
ACOH does not accept negative values. It should accept negative values as this is a valid scenario.

**Comment by lukeramones** [comment]
ACOH can and SHOULD accept negative values. This is managed by the accounting department as deficit of an account and will be fixed by adding cash on future trasactions.

**Comment by nikkinicholasromero** [comment]
Issue fixed in ccaa6aa1370a1e63072f1e7b1c50dd573ef8576b
